###
GET http://localhost:3006/api/config/gerencias/serviciosgerencias
###
GET http://localhost:3006/api/config/gerencias/serviciosgerencias/15

###
GET http://localhost:3006/api/config/gerencias/serviciosgerencias/porgerencia/5